on:
  pull_request:
    branches: ["develop"]
  push:
    branches: ["develop"]

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4

      - name: "Compliment"
        run: echo "Such code much pErfomant Wow!1!!!"

      - name: "Greet"
        run: echo Well hello there!
      
      - name: Install butler
        run: |
          mkdir cool
          touch cool/index.html
          zip -r cool.zip cool

          echo Installing Buttler
          curl -sS -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          ./butler -V

          echo Buttler installed!

          export BUTLER_API_KEY="${{ secrets.BUTLER_API_KEY }}"
          ./butler push cool.zip pyramid-seph/github_actions_test:web-stable